apiVersion: v2
name: elcicd-chart
description: |-
  A generic helm chart used to deploy any size group of components onto a kubernetes cluster.
  Library charts included: elcicd-renderer, el-cicd-kubernetes, el-cicd-common.

type: application

version: "0.1.0"

dependencies:
- name: elcicd-renderer
  version: 0.1.0
  repository: file://../elcicd-renderer
- name: elcicd-kubernetes
  version: 0.1.0
  repository: file://../elcicd-kubernetes
- name: elcicd-common
  version: 0.1.0
  repository: file://../elcicd-common