# GitHub Action that will automatically:
# - package all charts in a repo
# - push packaged charts to ghcr.io (GitHub container registry)
# - rebuild the index for https dependency references (i.e. https://raw.githubusercontent.com/.../charts)
#
# Action will only run on push and pull_request events
# Assumes all charts are stored in a <repo>/charts directory

name: Update Helm Chart Repository

on:
  push:
    branches:
    - main
    paths:
    - 'charts/**'

  pull_request_target:
    branches:
    - main
    paths:
    - 'charts/**'
    types:
      - closed

  workflow_dispatch:

jobs:
  package-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.name "elcicd"
        git config --global user.email "elcicd@donotreply.org"

    - name: Helm Installation
      uses: azure/setup-helm@v3
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Push Helm to ${{ github.repository_owner }} GitHub OCI Registry
      run: |
        set -ex
        cd charts
        for CHART_DIR in $(ls -d */)
        do
          echo ${{secrets.GITHUB_TOKEN}} | helm registry login -u NOT_NEEDED --password-stdin ghcr.io

          CHART_VERSION=$(grep '^version:' ./${CHART_DIR}/Chart.yaml | awk '{print $2}' | tr -d '"')
          CHART_NAME=$(grep '^name:' ./${CHART_DIR}/Chart.yaml | awk '{print $2}')

          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }} 
        done
